### PR TITLE
Added basic auth and X-Forwarded-For support

### PR DESCRIPTION
**Pull request by vrioux**
Here's a quick edit to add Basic HTTP authentication (users are requested to provide username and password when trying to use a service and that user/pass combo is sent to the database for authentication).

I also added the X-Forwarded-For HTTP header in the CGI variables so that any Oracle package or PLSQL code can read the real client IP when used through a proxy or load balancer.

Finally, I also Dockerized the application so that it can be build as a Docker image and then run on Docker platforms easily.

### CODE REVIEW

**Comment by vrioux** [comment]
Hi @doberkofler, anything I can do to have this PR accepted?

**Comment by doberkofler** [comment]
@vrioux Thank you very much for your work. I'm currently reviewing your changes and need a little more time. May I ask if and how you are currently using node_plsql?

**Comment by vrioux** [comment]
We're evaluating its usage in replacement of mod_plsql for our applications.  We didn't have time to evaluate it completely, but one thing that was immediately seen as missing is Basic HTTP auth mechanism, which is why I decided to go ahead and see if it could be added easily.

**Comment by doberkofler** [comment]
Dear @vrioux. Sorry it took me so long to review your very helpful changes but I was busy with my regular job.

I have now reviewed your changes and there a a few problems with your pull request:
- eslint reports some warnings (run gulp lint)
- quite a few unit tests fail (run gulp test)
- the shutdown from the status page generates an error

I therefore decided to take over your changes in multiple steps instead of merging your pull request:
- I will first upgrade all dependencies (already pushed)
- Then make sure that NodeJS 6 and 7 are supported (already pushed)
- Then add your changes for supporting "X-Forwarded-For" (already pushed)
- Then add your changes for supporting "basic auth"
- Finally have a look into Docker that I've never used before

Thank you again for your interest and help!

**Comment by doberkofler** [comment]
@vrioux the latest release 0.9.0 now contains basic auth and X-Forwarded-For support.
Thank you again!

**Pull request closed without merging**
